config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :volunteers, except: :new
  get "hosts/new" => "volunteers#new", defaults: {type: Volunteer.types[:host]}
  get "realocators/new" => "volunteers#new", defaults: {type: Volunteer.types[:realocator]}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  enum type: {
    host: "HOST",
    realocator: "REALOCATOR"
  }

  def is_host?
    self.type == Volunteer.types[:host]
  end

  def is_realocator?
    self.type == Volunteer.types[:realocator]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :destroy]

  # GET /volunteers
  # GET /volunteers.json
  def index
    @volunteers = Volunteer.all
  end

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
  end

  # GET /volunteers/new
  def new
    @volunteer = Volunteer.new
    @volunteer.type = params[:type]
  end

  # GET /volunteers/1/edit
  def edit
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    @volunteer = Volunteer.new(volunteer_params)

    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully created.' }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1
  # PATCH/PUT /volunteers/1.json
  def update
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully updated.' }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @volunteer.destroy
    respond_to do |format|
      format.html { redirect_to volunteers_url, notice: 'Volunteer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volunteer_params
      params.require(:volunteer).permit(:name, :lastname, :email, :host_capacity, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def block_to_partial(partial_name, options={}, &block)
    options.merge!(body: capture(&block))
    concat(render(partial: partial_name, locals: options))
  end

  def modal_form(modal_id, title, options={}, &block)
    block_to_partial('home/modal_form', options.merge(title: title, modal_id: modal_id), &block)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/home/_call_action_card.html.erb
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="http://via.placeholder.com/286x180" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= title%></h5>
    <p class="card-text"><%= description%></p>
    <a href="<%=url_to%>" class="btn btn-primary" ><%= url_text_description%></a>
  </div>
</div>

app/views/home/_modal_form.html.erb
<div class="modal fade" id="<%=modal_id%>" tabindex="-1" role="dialog" aria-labelledby="<%=modal_id%>Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="<%=modal_id%>lLabel"><%=title%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= body %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary">Registrame!</button>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row mainblock" id="feature">
    <iframe width="1200" height="500" src="https://www.youtube.com/embed/7_sArxpUQho" frameborder="0" allow="autoplay; encrypted-media"
      allowfullscreen></iframe>
  </div>
  <div class="row mainblock" id="manifesto">
    <h1>Manifesto</h1>

    <p>Yeah, I like animals better than people sometimes... Especially dogs. Dogs are the best. Every time you come home, they act
      like they haven't seen you in a year. And the good thing about dogs... is they got different dogs for different people.
      Like pit bulls. The dog of dogs. Pit bull can be the right man's best friend... or the wrong man's worst enemy. You going
      to give me a dog for a pet, give me a pit bull. Give me... Raoul. Right, Omar? Give me Raoul. </p>

    <p>Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you
      see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when
      you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because
      you're here shopping for an infant named Jeb. </p>

    <!-- end slipsum code -->
  </div>
  <div class="row mainblock" id="signup">
    <div class="col" id="host">
      <%= render "call_action_card",
          title: "Alberga a alguien",
          description: "Brinda un techo temporal a una de estas familias afectadas",
          url_to: hosts_new_path,
          url_text_description: "Registrate"%>
    </div>
    <div class="col" id="realocator">
      <%= render "call_action_card",
          title: "Busca un espacio",
          description: "Se parte del equipo de personas que ayuden a buscar un espacio permanente para esta comunidad",
          url_to: realocators_new_path,
          url_text_description: "Registrate"%>
    </div>
    <div class="col" id="Share">
      <%= render "call_action_card",
              title: "Comparte",
              description: "Ayudanos a difundir esta iniciativa y que estas familias tengan un nuevo techo para vivir",
              url_to: "",
              url_text_description: "Registrate"%>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Samaritanos por Espino</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#feature">Iniciativa</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#manifesto">Manifesto</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#signup">Registrate</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SamaritanEspino</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/volunteers/_form.html.erb
<%= form_with(model: volunteer, local: true) do |form| %>
  <%= form.hidden_field :type %>
  <% if volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

      <ul>
      <% volunteer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <% if volunteer.is_host? %>
    <div class="field">
      <%= form.label :host_capacity %>
      <%= form.number_field :host_capacity %>
    </div>
  <%end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/volunteers/edit.html.erb
<h1>Editing Volunteer</h1>

<%= render 'form', volunteer: @volunteer %>

<%= link_to 'Show', @volunteer %> |
<%= link_to 'Back', volunteers_path %>

app/views/volunteers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Volunteers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Host capacity</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volunteers.each do |volunteer| %>
      <tr>
        <td><%= volunteer.name %></td>
        <td><%= volunteer.lastname %></td>
        <td><%= volunteer.email %></td>
        <td><%= volunteer.host_capacity %></td>
        <td><%= volunteer.type %></td>
        <td><%= link_to 'Show', volunteer %></td>
        <td><%= link_to 'Edit', edit_volunteer_path(volunteer) %></td>
        <td><%= link_to 'Destroy', volunteer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Volunteer', new_volunteer_path %>

app/views/volunteers/new.html.erb
<%if  @volunteer.is_host? %>
  <h1>Gracias por albergar a una famila</h1>
<%else%>
  <h1>Gracias por buscar un nuevo hogar a una famila</h1>
<%end%>

<%= render 'form', volunteer: @volunteer %>

<%= link_to 'Back', volunteers_path %>

app/views/volunteers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @volunteer.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @volunteer.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @volunteer.email %>
</p>

<p>
  <strong>Host capacity:</strong>
  <%= @volunteer.host_capacity %>
</p>

<p>
  <strong>Type:</strong>
  <%= @volunteer.type %>
</p>

<%= link_to 'Edit', edit_volunteer_path(@volunteer) %> |
<%= link_to 'Back', volunteers_path %>